package com.example.sales.Enum;

public enum CategoryEnum {
    CLOTHING_AND_APPAREL,
    ELECTRONICS,
    BEAUTY_AND_PERSONAL_CARE,
    HOME_AND_GARDEN,
    SPORTS_AND_OUTDOORS,
    HEALTH_AND_WELLNESS,
    TOYS_AND_GAMES,
    BOOKS_AND_MEDIA,
    AUTOMOTIVE,
    FOOD_AND_BEVERAGES,
    JEWELRY_AND_ACCESSORIES,
    PET_SUPPLIES,
    OFFICE_SUPPLIES,
    ARTS_AND_CRAFTS,
    BABY_AND_KIDS
}
